// <auto-generated />
using System;
using AppointmentSystemServer.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentSystemServer.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322213944_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Emergency"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Outpatient"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inpatient"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gynecology"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pathology"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Anesthesia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 16,
                            Name = "ENT"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Laboratory"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Physiotherapy"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Urology"
                        });
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Michael",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            FirstName = "Sarah",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            FirstName = "David",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            FirstName = "Emily",
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            FirstName = "James",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            FirstName = "Jessica",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            FirstName = "William",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            FirstName = "Sophia",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 11,
                            FirstName = "Daniel",
                            LastName = "Hernandez"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 12,
                            FirstName = "Olivia",
                            LastName = "Lopez"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 13,
                            FirstName = "Matthew",
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 14,
                            FirstName = "Isabella",
                            LastName = "Perez"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 15,
                            FirstName = "Alexander",
                            LastName = "Hall"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 16,
                            FirstName = "Mia",
                            LastName = "Young"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 17,
                            FirstName = "Ethan",
                            LastName = "Allen"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 18,
                            FirstName = "Ava",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 19,
                            FirstName = "Benjamin",
                            LastName = "Scott"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 20,
                            FirstName = "Charlotte",
                            LastName = "Green"
                        });
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AppointmentSystemServer.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentSystemServer.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("AppointmentSystemServer.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AppointmentSystemServer.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentSystemServer.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentSystemServer.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
